### PR TITLE
Update howto.rst

### PR DESCRIPTION
**Pull request by sandykurniawan19**
add new a translation tool [Vim](http://www.vim.org/scripts/script.php?script_id=695) , using .po editor .

### CODE REVIEW

**Comment by jayvdb** [comment]
Does Attesoro support `.po` files?

**Comment by sandykurniawan19** [comment]
i'm forget mr, sorry , thanks mr @jayvdb

**Comment by sandykurniawan19** [comment]
mr @jayvdb , how about with Vim Editor ?

**Comment by jayvdb** [comment]
I leave that for the maintainers to decide.

**Comment by dwaynebailey** [comment]
@sandykurniawan19 thanks for the contribution:

* Attesoro - just a properties editor, so nope we don't want to cloud and confuse users with that
* Vim - a useful extension but a bt too geeky for our audience, again too many choices is one of the things that often prevent less skilled localisers from contributing.

**Pull request closed without merging**
